# Generated by Django 2.2 on 2020-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w_app', '0002_deetcity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deetcity',
            old_name='deetname',
            new_name='name',
        ),
    ]
